apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-storage
  namespace: dev
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi