apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-05-23T21:09:45Z"
  generation: 2
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: dev
  resourceVersion: "3773"
  selfLink: /apis/apps/v1/namespaces/dev/deployments/nginx-deploy
  uid: 8963081c-f3ba-4ad5-884b-d8b99cd1f241
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy
    spec:
      containers:
      - env:
        - name: dev
          value: 1.0.0.0
        image: nginx
        imagePullPolicy: Always
        name: nginx
        volumeMounts:
        - name: nginx-storage
          mountPath: /data/
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-storage
